# Generated by Django 6.0.1 on 2026-01-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecurso',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria_recurso',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('cuestionario_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('tiempo_limite_minutos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cuestionario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('es_administrador', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='IntentoCuestionario',
            fields=[
                ('intento_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('puntaje_total', models.IntegerField(blank=True, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='core.cuestionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='core.usuario')),
            ],
            options={
                'db_table': 'intento_cuestionario',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('puntos', models.IntegerField(default=1)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.cuestionario')),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('opcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.pregunta')),
            ],
            options={
                'db_table': 'opcion_respuesta',
            },
        ),
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('recurso_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_recurso', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_recurso', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('es_publico', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='core.categoriarecurso')),
            ],
            options={
                'db_table': 'recurso_educativo',
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('respuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.intentocuestionario')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
            ],
            options={
                'db_table': 'respuesta_usuario',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('publicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('es_anonima', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('editada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='core.usuario')),
            ],
            options={
                'db_table': 'publicacion',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.usuario')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
    ]
