# Generated by Django 6.0.1 on 2026-01-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_es_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='es_administrador',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
